#禁用安全机制，可查看自带的接口，发布时禁用
management:
  security:
    enabled: true

#端口号.
server:
  port : ${port}
  session:
    #会话超时（秒）,10分钟。
    timeout: 600
  max-http-header-size: 8192

logging:
  level:
    root: info
  file: log/console.log

spring:
  datasource:
    url: jdbc:mysql://${db.ip}:${db.port}/GATools?useUnicode=true&characterEncoding=utf-8
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.DriverSpy


